#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InspectionApp.Resource", IsApplication=true)]

namespace InspectionApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BusinessLayer.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessLayer.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
			global::BusinessObjects.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessObjects.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int Answers_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_light = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int my_red = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int my_white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int HomePage = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Upload = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090018
			public const int Answer1 = 2131296280;
			
			// aapt resource value: 0x7f09000d
			public const int AuditDescription = 2131296269;
			
			// aapt resource value: 0x7f090033
			public const int AuditListingView = 2131296307;
			
			// aapt resource value: 0x7f090016
			public const int Camera1 = 2131296278;
			
			// aapt resource value: 0x7f09001a
			public const int Camera2 = 2131296282;
			
			// aapt resource value: 0x7f090020
			public const int Camera3 = 2131296288;
			
			// aapt resource value: 0x7f090024
			public const int Camera4 = 2131296292;
			
			// aapt resource value: 0x7f090031
			public const int FillAudit = 2131296305;
			
			// aapt resource value: 0x7f090038
			public const int Play = 2131296312;
			
			// aapt resource value: 0x7f090036
			public const int Record = 2131296310;
			
			// aapt resource value: 0x7f090039
			public const int SampleVideoView = 2131296313;
			
			// aapt resource value: 0x7f090028
			public const int SaveQuestion = 2131296296;
			
			// aapt resource value: 0x7f090037
			public const int Stop = 2131296311;
			
			// aapt resource value: 0x7f090032
			public const int ViewAudit = 2131296306;
			
			// aapt resource value: 0x7f090010
			public const int absoluteLayout1 = 2131296272;
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int auto = 2131296266;
			
			// aapt resource value: 0x7f09002f
			public const int back = 2131296303;
			
			// aapt resource value: 0x7f090034
			public const int btnBack = 2131296308;
			
			// aapt resource value: 0x7f090029
			public const int btnBackToList = 2131296297;
			
			// aapt resource value: 0x7f090030
			public const int btnMap = 2131296304;
			
			// aapt resource value: 0x7f09000e
			public const int btnView = 2131296270;
			
			// aapt resource value: 0x7f09002a
			public const int button1 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int button2 = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int button3 = 2131296300;
			
			// aapt resource value: 0x7f090022
			public const int chkAnswer3 = 2131296290;
			
			// aapt resource value: 0x7f09000b
			public const int dark = 2131296267;
			
			// aapt resource value: 0x7f090014
			public const int eTextLocation = 2131296276;
			
			// aapt resource value: 0x7f090019
			public const int fileQuestion1 = 2131296281;
			
			// aapt resource value: 0x7f09001f
			public const int fileQuestion2 = 2131296287;
			
			// aapt resource value: 0x7f090023
			public const int fileQuestion3 = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int fileQuestion4 = 2131296295;
			
			// aapt resource value: 0x7f090035
			public const int googlemap = 2131296309;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int icon_only = 2131296263;
			
			// aapt resource value: 0x7f09002e
			public const int imageCamera = 2131296302;
			
			// aapt resource value: 0x7f090017
			public const int labelQuestion1 = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int labelQuestion2 = 2131296283;
			
			// aapt resource value: 0x7f090021
			public const int labelQuestion3 = 2131296289;
			
			// aapt resource value: 0x7f090025
			public const int labelQuestion4 = 2131296293;
			
			// aapt resource value: 0x7f09000c
			public const int light = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int linearLayout1 = 2131296271;
			
			// aapt resource value: 0x7f090015
			public const int next = 2131296277;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f09001e
			public const int radio_No = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int radio_Yes = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int rdoQuestion2 = 2131296284;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f090026
			public const int spinnerAnswer4 = 2131296294;
			
			// aapt resource value: 0x7f090012
			public const int spnTemplates = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f09002d
			public const int takePicture = 2131296301;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f090011
			public const int textView1 = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int textView2 = 2131296275;
			
			// aapt resource value: 0x7f090009
			public const int wide = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuditDetailItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuditDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AuditQuestionAnswers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Camera = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MapView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Video = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040013
			public const int Answer_prompt = 2130968595;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040016
			public const int back = 2130968598;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_enable_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_enable_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_enable_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_button = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_title = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_notification_ticker = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_unsupported_text = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_update_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_wear_update_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_open_on_phone = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int common_signin_button_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_signin_button_text_long = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int openCamera = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int takePicture = 2130968597;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int MyCustomTheme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
