#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InspectionApp.Resource", IsApplication=true)]

namespace InspectionApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BusinessLayer.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessLayer.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
			global::BusinessObjects.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessObjects.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Answers_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int my_red = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int my_white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HomePage = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Upload = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int Answer1 = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int AuditDescription = 2131230720;
			
			// aapt resource value: 0x7f080020
			public const int AuditListingView = 2131230752;
			
			// aapt resource value: 0x7f080009
			public const int Camera1 = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int Camera2 = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int Camera3 = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int Camera4 = 2131230743;
			
			// aapt resource value: 0x7f080021
			public const int FillAudit = 2131230753;
			
			// aapt resource value: 0x7f080027
			public const int Play = 2131230759;
			
			// aapt resource value: 0x7f080025
			public const int Record = 2131230757;
			
			// aapt resource value: 0x7f080028
			public const int SampleVideoView = 2131230760;
			
			// aapt resource value: 0x7f08001b
			public const int SaveQuestion = 2131230747;
			
			// aapt resource value: 0x7f080026
			public const int Stop = 2131230758;
			
			// aapt resource value: 0x7f08001f
			public const int ViewAudit = 2131230751;
			
			// aapt resource value: 0x7f080003
			public const int absoluteLayout1 = 2131230723;
			
			// aapt resource value: 0x7f08001e
			public const int back = 2131230750;
			
			// aapt resource value: 0x7f080001
			public const int btnView = 2131230721;
			
			// aapt resource value: 0x7f080022
			public const int button1 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int button2 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int button3 = 2131230756;
			
			// aapt resource value: 0x7f080015
			public const int chkAnswer3 = 2131230741;
			
			// aapt resource value: 0x7f080007
			public const int eTextLocation = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int fileQuestion1 = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int fileQuestion2 = 2131230738;
			
			// aapt resource value: 0x7f080016
			public const int fileQuestion3 = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int fileQuestion4 = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int imageCamera = 2131230749;
			
			// aapt resource value: 0x7f08000a
			public const int labelQuestion1 = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int labelQuestion2 = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int labelQuestion3 = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int labelQuestion4 = 2131230744;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int next = 2131230728;
			
			// aapt resource value: 0x7f080011
			public const int radio_No = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int radio_Yes = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int rdoQuestion2 = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int spinnerAnswer4 = 2131230745;
			
			// aapt resource value: 0x7f080005
			public const int spnTemplates = 2131230725;
			
			// aapt resource value: 0x7f08001c
			public const int takePicture = 2131230748;
			
			// aapt resource value: 0x7f080004
			public const int textView1 = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int textView2 = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuditDetailItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuditDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AuditQuestionAnswers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Camera = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Video = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int Answer_prompt = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int back = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int openCamera = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int takePicture = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyCustomTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
