#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InspectionApp.Resource", IsApplication=true)]

namespace InspectionApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BusinessLayer.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessLayer.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
			global::BusinessObjects.Resource.String.ApplicationName = global::InspectionApp.Resource.String.ApplicationName;
			global::BusinessObjects.Resource.String.Hello = global::InspectionApp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Answers_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HomePage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Upload = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int Answer1 = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int AuditDescription = 2131165184;
			
			// aapt resource value: 0x7f070021
			public const int AuditListingView = 2131165217;
			
			// aapt resource value: 0x7f070009
			public const int Camera1 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int Camera2 = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int Camera3 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int Camera4 = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int FillAudit = 2131165215;
			
			// aapt resource value: 0x7f070024
			public const int Play = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int Record = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int SampleVideoView = 2131165221;
			
			// aapt resource value: 0x7f07001b
			public const int SaveQuestion = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int Stop = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int ViewAudit = 2131165216;
			
			// aapt resource value: 0x7f070003
			public const int absoluteLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07001e
			public const int back = 2131165214;
			
			// aapt resource value: 0x7f070001
			public const int btnView = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int chkAnswer3 = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int eTextLocation = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int fileQuestion1 = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int fileQuestion2 = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int fileQuestion3 = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int fileQuestion4 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int imageCamera = 2131165213;
			
			// aapt resource value: 0x7f07000a
			public const int labelQuestion1 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int labelQuestion2 = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int labelQuestion3 = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int labelQuestion4 = 2131165208;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int next = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int radio_No = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int radio_Yes = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int rdoQuestion2 = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int spinnerAnswer4 = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int spnTemplates = 2131165189;
			
			// aapt resource value: 0x7f07001c
			public const int takePicture = 2131165212;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuditDetailItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuditDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AuditQuestionAnswers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Camera = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Video = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int Answer_prompt = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int back = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int openCamera = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int takePicture = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
